# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pass.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import random
import string

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(541, 230)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-10, 0, 551, 241))
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #DCE35B, stop:1 #45B649);\n"
"border-radius:5px")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(40, 80, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Zar")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #dd3e54, stop:1 #6be585);\n"
"border-radius:5px;\n"
"\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(150, 80, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Zar")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color:3px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButtonclose = QtWidgets.QPushButton(self.frame)
        self.pushButtonclose.setGeometry(QtCore.QRect(520, 10, 21, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(18)
        sizePolicy.setVerticalStretch(18)
        sizePolicy.setHeightForWidth(self.pushButtonclose.sizePolicy().hasHeightForWidth())
        self.pushButtonclose.setSizePolicy(sizePolicy)
        self.pushButtonclose.setMinimumSize(QtCore.QSize(18, 18))
        self.pushButtonclose.setSizeIncrement(QtCore.QSize(18, 18))
        self.pushButtonclose.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"border-radius:10px;")
        self.pushButtonclose.setText("")
        self.pushButtonclose.setObjectName("pushButtonclose")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButtonclose.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

       

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate

        
        self.pushButton.setText(_translate("MainWindow", "password"))
        self.pushButton.clicked.connect(self.pas)

#----movement mainwindow with mouse

    def mousePressEvent(self,evt):
            self.oldPos=evt.globalPos()
    def mouseMoveEvent(self,evt):
            delta=QPoint(evt.globalPos()-self.oldPos)
            self.move(self.x())+delta.x(),self.y+delta.y()
            self.oldPos=evt.globalPos()





        
    def pas(self):
        lower = string.ascii_lowercase
        upper = string.ascii_uppercase
        num = string.digits
        all = lower + upper + num 
        temp = random.sample(all,6)
        password = "".join(temp)
        self.label.setText(password)
if __name__ == "__main__" :
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
